### ISSUE TITLE
Dead 类指标为零

### ISSUE THREAD

**Issue by zqing10** [JiYuanFeng/MCTrans#13]
你好，请问为什么有一类的指标一直是0，上不去。
![QQ图片20220303230837](https://user-images.githubusercontent.com/62885530/156592383-a9b54b9c-6dd3-4859-9a99-85ba31397cf2.png)

**Comment by JiYuanFeng** [comment]
HI, 由于Dead属于非常难的类别，所以网络需要训练一段时间来拟合这些困难度高的func，下面贴的图一个是 Epoch35以及Epoch36， 从之前的记录上看，大概是这个阶段后dead类指标上升。
<img width="999" alt="image" src="https://user-images.githubusercontent.com/20653249/156594949-f22cc875-a669-4860-9c0a-a36d95e9dd83.png">
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/20653249/156594982-a6bc7150-cd85-46d6-82df-fe8fe0bd8695.png">

**Comment by zqing10** [comment]
![git](https://user-images.githubusercontent.com/62885530/156725285-22aadd2a-7baa-43e8-8716-a6df123ec9b3.png)
你好，请问为什么打开目录就一个数据集

**Comment by JiYuanFeng** [comment]
你好，暂时没有时间去整理其他数据集，你可以按上图格式组织

**Comment by zqing10** [comment]
感谢回复。请问按照原来的参数设置，大概需要训练多少epho？为什么寻训练不出论文的指标

**Comment by JiYuanFeng** [comment]
按照默认的config训练就可以得到对应的指标



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月4日(星期五) 下午4:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [JiYuanFeng/MCTrans] Dead 类指标为零 (Issue #13)





 
感谢回复。请问按照原来的参数设置，大概需要训练多少epho？为什么寻训练不出论文的指标
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zqing10** [comment]
你好，请问为什么按照这个修改完，跑出来的最佳指标只有67.13






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JiYuanFeng/MCTrans"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月4日(星期五) 下午4:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JiYuanFeng/MCTrans] Dead 类指标为零 (Issue #13)





 按照默认的config训练就可以得到对应的指标 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2022年3月4日(星期五) 下午4:24 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; "State ***@***.***&amp;gt;;  
 主题: Re: [JiYuanFeng/MCTrans] Dead 类指标为零 (Issue #13) 
 
 
 
 
 
   
 感谢回复。请问按照原来的参数设置，大概需要训练多少epho？为什么寻训练不出论文的指标 
   
 — 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android.  
 You are receiving this because you modified the open/close state.Message ID: ***@***.***&amp;gt; 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
