### ISSUE TITLE
CA module

### ISSUE THREAD

**Issue by qq274983722** [JiYuanFeng/MCTrans#14]
Dear Author
I don't see the use of CA module in mctrans.py. Is the CA module useless?

**Comment by JiYuanFeng** [comment]
hi， please check https://github.com/JiYuanFeng/MCTrans/blob/01afe3b589e779730b04964b6419b2b5afb7e909/mctrans/models/heads/mctrans_aux_head.py#:~:text=class%20MCTransAuxHead(nn.Module)%3A

**Comment by qq274983722** [comment]
> 您好，请查看https://github.com/JiYuanFeng/MCTrans/blob/01afe3b589e779730b04964b6419b2b5afb7e909/mctrans/models/heads/mctrans_aux_head.py#:~:text=class%20MCTransAuxHead(nn.Module)%3A


Thank you very much for your reply
