### ISSUE TITLE
The implement of NonLocalUNet is quiet different from the official implement

### ISSUE THREAD

**Issue by Lloyd-Pottiger** [JiYuanFeng/MCTrans#15]
The implement of NonLocalUNet in this repo is VGG encoder + NonLocal center + UNet decoder, but the official implement is: replacing upsample and downsample with Global Aggregation Block,  reduce the layers of UNet and replace the Concatenation with Add. 
Refer to https://github.com/divelab/Non-local-U-Nets、https://arxiv.org/abs/1812.04103

**Comment by JiYuanFeng** [comment]
Hi, thank you for pointing this out. In fact, in the paper, we did not compare with NonLocalUNet, instead of comparing with the method of UNet + NonLocal operation.

**Comment by Lloyd-Pottiger** [comment]
You are right. Maybe you should change NonLocalUNet into UNet+NonLocal in [README](https://github.com/JiYuanFeng/MCTrans#model-zoo) which may be missleading.

**Comment by JiYuanFeng** [comment]
Yes, thank you for the suggestion!
