### ISSUE TITLE
In the data you provide, the mask is pure black

### ISSUE THREAD

**Issue by 675492062** [JiYuanFeng/MCTrans#18]
![image](https://user-images.githubusercontent.com/7007669/161177627-d69ae7bb-0be2-43ef-99c2-900fa9a09a28.png)

**Comment by 675492062** [comment]
I downloaded it from the Google disk you uploaded. Is this normal?

**Comment by JiYuanFeng** [comment]
Hi, that's ok. The image contains pixels in the range [0, 5], so the mask looks pure black.

**Comment by 675492062** [comment]
ok，三克油，感谢热心的回复。
