### ISSUE TITLE
最后的指标和论文不一致

### ISSUE THREAD

**Issue by zqing10** [JiYuanFeng/MCTrans#19]
![1](https://user-images.githubusercontent.com/62885530/163704722-86a3ac66-8459-45db-8be3-ca0604806860.png)
你好，请问为什么按照这个修改完，跑出来的最佳指标只有67.13
![QQ图片20220417101219](https://user-images.githubusercontent.com/62885530/163704738-e0869bcb-0838-42dc-8902-a3f19042ad23.png)

**Comment by JiYuanFeng** [comment]
Please provide the configuration details of your running experiment. Why do you mean "请问为什么按照这个修改完"?

**Comment by JiYuanFeng** [comment]
OK, I understand what you mean..., as you follow the modification in https://github.com/JiYuanFeng/MCTrans/issues/16#issuecomment-1069124898. The original code can be run normally if you use the monai==0.5.3,  please not change anything.  I have checked the previous experiment. Using default configuration can easy to achieve a validation score of 68 in the first fold. 
<img width="1594" alt="image" src="https://user-images.githubusercontent.com/20653249/163723344-cb8704c6-c9da-4254-aad3-ab538e070fa9.png">

**Comment by JiYuanFeng** [comment]
If you have update or any questions, please re-open this issue
