### ISSUE TITLE
About the Auxillary Loss

### ISSUE THREAD

**Issue by GuoQingqing** [JiYuanFeng/MCTrans#22]
Hi!
Thanks for your code. I have a question about the Auxillary Loss.  What's the gt for Auxillary Loss? Thank you very much!

**Comment by JiYuanFeng** [comment]
Hi, We use the unique value of mask as the classification label

**Comment by GuoQingqing** [comment]
Sorry, I can not follow you. What does “the unique value of mask” mean？Could you please explain it detailly? Thank you very much!
