### ISSUE TITLE
请问使用.npy格式的数据和使用.png格式的数据有区别吗

### ISSUE THREAD

**Issue by Allen-Zhou729** [JiYuanFeng/MCTrans#23]
首先感谢作者的工作！您提供的PanNuke数据集里面有split-images(masks)-npy和split-images(masks)，前者是.npy格式，后者是.png格式，请问使用这两种不同格式的数据集进行训练和测试是等价的吗？因为我load了npy格式的，发现其中的数据也是0~255的，和png格式的数据是一样的，是不是代表着使用.png格式的数据可以获得和.npy格式数据的同样效果？感谢！

**Comment by JiYuanFeng** [comment]
Hi, sorry for the late reply. They are equal!
