### ISSUE TITLE
unet_vgg32_d5_256x256_400ep_pannuke.py

### ISSUE THREAD

**Issue by yangyang117** [JiYuanFeng/MCTrans#4]
你好，我在运行程序时，出现了如下错误：
FileNotFoundError: file "/home/yyang17/projects/MCTrans/configs/debug/unet_vgg32_d5_256x256_400ep_pannuke.py" does not exist
在项目里面搜索 unet_vgg32_d5_256x256_400ep_pannuke.py 也没有发现，请问是否有部分模型文件没有上传呢？

**Comment by JiYuanFeng** [comment]
你好，不好意思，我的sh文件忘记更新了，正确的sh 内容为：
#!/usr/bin/env bash
CFG="configs/pannuke-vgg32/unet_vgg32_d5_256x256_400ep_pannuke.py"
WORK_DIR=$(echo ${CFG%.*} | sed -e "s/configs/work_dirs/g")/
python3 tools/train.py ${CFG} --work-dir ${WORK_DIR} --gpus 1

配置文件是存在目前的项目中的，路径为:configs/pannuke-vgg32/mctrans_vgg32_d5_256x256_400ep_pannuke.py

已修正上传
