### ISSUE TITLE
实验结果与论文不同

### ISSUE THREAD

**Issue by yimuu** [JiYuanFeng/MCTrans#5]
+---------------------------+--------+-------+-------+--------+-----------+--------+
|           Class           |  Dice  |  Acc  |  IoU  | Fscore | Precision | Recall |
+---------------------------+--------+-------+-------+--------+-----------+--------+
|         Background        | 142.16 | 600.0 | 245.8 | 142.16 |   80.63   | 600.0  |
|         Neoplastic        |  0.0   |  0.0  |  0.0  |  nan   |    nan    |  0.0   |
|        Inflammatory       |  0.0   |  0.0  |  0.0  |  nan   |    nan    |  0.0   |
|         Connective        |  0.0   |  0.0  |  0.0  |  nan   |    nan    |  0.0   |
|            Dead           |  0.0   |  0.0  |  0.0  |  nan   |    nan    |  0.0   |
| Non-Neoplastic Epithelial |  0.0   |  0.0  |  0.0  |  nan   |    nan    |  0.0   |
+---------------------------+--------+-------+-------+--------+-----------+--------+
这是我跑完模型它在log中统计的结果，为什么所有结果都是0？
而且我没有发现生成的预测图。

**Comment by JiYuanFeng** [comment]
please install monai == 0.5.3, now, we have not provided a visual tool in the current version.

**Comment by yimuu** [comment]
在monai=0.6 ,array.py中softmax与argmax都设置dim=0，所以导致结果不正确
