### ISSUE TITLE
gpu memory

### ISSUE THREAD

**Issue by jjjcs** [JiYuanFeng/MCTrans#6]
Hi,
Thanks for your great job, i like your algorithm very much.
i have been trying to reproduce your result, may i ask how big is your gpu memory, i have 16GB, but always "CUDA out of memory."

**Comment by JiYuanFeng** [comment]
Hi, 
I run all the experiments on one V100 GPU. The GPU utilization is shown below. Maybe you can reduce the batch num to fit the model and see how the experiments look like,  the batch nums should not affect too much.


![image](https://user-images.githubusercontent.com/20653249/127866882-82b0a5fd-4b20-4b3b-9731-0af735156d05.png)

**Comment by jjjcs** [comment]
我不确定这个算法是不是对batch敏感，已经试着减少batch size了，非常感谢。
